version: '3.7'

volumes:
  prometheus:

networks:
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
    ports:
      - 9090:9090
    networks:
      - back-tier

  node-exporter:
    container_name: node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    image: prom/node-exporter:v1.3.1
    volumes:
      - /proc:/host/proc
      - /sys:/host/sysfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sysfs'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100
    networks:
      - back-tier