version: '3'

volumes:
  alertmanager:
  grafana:
  prometheus:

networks:
  back-tier:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    ports:
      - 80:8080
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
    ports:
      - 9090:9090
    networks:
      - back-tier

  blackbox:
    container_name: blackbox
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox:/config
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    networks:
      - back-tier
