version: '3.7'

volumes:
  alertmanager:
  prometheus:

networks:
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=10GB'
    ports:
      - 9090:9090
    networks:
      - back-tier

  node-exporter:
    container_name: node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    image: prom/node-exporter:v1.3.1
    volumes:
      - /proc:/host/proc
      - /sys:/host/sysfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sysfs'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    ports:
      - 9100:9100
    networks:
      - back-tier

  alertmanager:
    container_name: alertmanager
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    image: prom/alertmanager:v0.24.0
    volumes:
      - alertmanager:/alertmanager
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - back-tier

  flask_webserver:
    build: ./test_tools/
    container_name: flask_webserver
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    image: andredeo/flask_webserver:1.0.0
    ports:
     - 8000:8000
    networks:
      - back-tier

  pushgateway:
    container_name: pushgateway
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    command:
      - '--web.enable-admin-api'
    restart: on-failure:5
    image: prom/pushgateway:v1.4.3
    ports:
      - 9091:9091
    networks:
      - back-tier

  blackbox:
    container_name: blackbox
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 200m
    image: prom/blackbox-exporter:v0.22.0
    volumes:
      - ./blackbox:/config
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    networks:
      - back-tier