# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).


rule_files:
  - 'alert.conf'

 # A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: [ 'prometheus:9090']

  - job_name: 'notebook'
    static_configs:
    - targets: [ 'node-exporter:9100']

  - job_name: 'demo'
    static_configs:
    - targets: [ 'demo:8001']

  - job_name: 'blackbox_http_2xx'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    http_sd_configs:
      - url: 'https://gist.githubusercontent.com/andreyev/1e82bc5786460858303cea9b8ae7ff47/raw/d8b734f9a099d89579d453c14e975f7b162e9530/test.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
